"""add_investment_tables

Revision ID: dd69ecde196e
Revises: df013ec94309
Create Date: 2026-05-31 12:40:14.663683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_investment_tables

Revision ID: dd69ecde196e
Revises: df013ec94309
Create Date: 2026-05-31 12:40:14.663683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd69ecde196e'
down_revision: Union[str, Sequence[str], None] = 'df013ec94309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_appetite', sa.String(length=50), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    
    # Check if category column exists in receipt_items
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('receipt_items')]
    if 'category' not in columns:
        op.add_column('receipt_items', sa.Column('category', sa.String(length=80), server_default='khac', nullable=False))
    else:
        op.alter_column('receipt_items', 'category',
                   existing_type=sa.VARCHAR(length=80),
                   nullable=False,
                   existing_server_default=sa.text("'khac'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('receipt_items')]
    if 'category' in columns:
        op.drop_column('receipt_items', 'category')
        
    op.drop_table('investment_profiles')
    op.drop_table('investment_assets')
    # ### end Alembic commands ###
